export enum OPCode {
    DISPATCH = 0,
    HEARTBEAT = 1,
    IDENTIFY = 2,
    PRESENCE_UPDATE = 3,
    VOICE_STATE_UPDATE = 4,
    RESUME = 6,
    RECONNECT = 7,
    REQUEST_GUILD_MEMBERS = 8,
    INVALID_SESSION = 9,
    HELLO = 10,
    HEARTBEAT_ACK = 11
}

export enum GatewayEvent {
    READY = 'READY',
    RESUMED = 'RESUMED',
    APPLICATION_COMMAND_CREATE = 'APPLICATION_COMMAND_CREATE',
    APPLICATION_COMMAND_UPDATE = 'APPLICATION_COMMAND_UPDATE',
    APPLICATION_COMMAND_DELETE = 'APPLICATION_COMMAND_DELETE',
    CHANNEL_CREATE = 'CHANNEL_CREATE',
    CHANNEL_UPDATE = 'CHANNEL_UPDATE',
    CHANNEL_DELETE = 'CHANNEL_DELETE',
    CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE',
    GUILD_CREATE = 'GUILD_CREATE',
    GUILD_UPDATE = 'GUILD_UPDATE',
    GUILD_DELETE = 'GUILD_DELETE',
    GUILD_BAN_ADD = 'GUILD_BAN_ADD',
    GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE',
    GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE',
    GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE',
    GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD',
    GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE',
    GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE',
    GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK',
    GUILD_ROLE_CREATE = 'GUILD_ROLE_CREATE',
    GUILD_ROLE_UPDATE = 'GUILD_ROLE_UPDATE',
    GUILD_ROLE_DELETE = 'GUILD_ROLE_DELETE',
    INTERACTION_CREATE = 'INTERACTION_CREATE',
    INVITE_CREATE = 'INVITE_CREATE',
    INVITE_DELETE = 'INVITE_DELETE',
    MESSAGE_CREATE = 'MESSAGE_CREATE',
    MESSAGE_UPDATE = 'MESSAGE_UPDATE',
    MESSAGE_DELETE = 'MESSAGE_DELETE',
    MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK',
    MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
    MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
    MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL',
    MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI',
    PRESENCE_UPDATE = 'PRESENCE_UPDATE',
    STAGE_INSTANCE_CREATE = 'STAGE_INSTANCE_CREATE',
    STAGE_INSTANCE_UPDATE = 'STAGE_INSTANCE_UPDATE',
    STAGE_INSTANCE_DELETE = 'STAGE_INSTANCE_DELETE',
    THREAD_CREATE = 'THREAD_CREATE',
    THREAD_UPDATE = 'THREAD_UPDATE',
    THREAD_DELETE = 'THREAD_DELETE',
    THREAD_LIST_SYNC = 'THREAD_LIST_SYNC',
    THREAD_MEMBER_UPDATE = 'THREAD_MEMBER_UPDATE',
    THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE',
    TYPING_START = 'TYPING_START',
    USER_UPDATE = 'USER_UPDATE',
    VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE',
    VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE',
    WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE'
}

export enum Endpoint {
    GATEWAY = 'wss://gateway.discord.gg/?v=9&encoding=json',
    REST = 'https://discord.com/api/v9'
}

export const ErrorCodeList = Object.freeze([4004, 4010, 4011, 4012, 4013, 4014])
export const DropCodeList = Object.freeze([4007, 4009])
